$$ {\huge \text{ Disciplina: Lógica Fuzzy }}\\  \\  \text{ Cap 9 - Tomada de Decisão em Sistemas Fuzzy / Redes Bayesianas}\\
\ \  \ \ \ \ 
\\
 { \it  \text{ Discente: Prof. Dr. João Fernando }  }
 \\
\text{ Monitor: Arnaldo Araújo} \\
\text{ Mestrado e Doutorado em Ciências da Computação - UFC }$$


In [1]:
import numpy as np
from pandas import DataFrame
from numpy import *
from IPython.display import Latex
import skfuzzy as fuzz
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from matplotlib.font_manager import FontProperties
%matplotlib inline 

# EXEMPLO 9.9

$ {\large \text{ Escolha de Placas PCB de acordo com a densidade do circuito }}$
<hr/>
${\large \textit {Tipos de Placas - Single-Layer PCB , Double-Layer PCB, Four-Layer PCB, Six-Layer PCB}}$

ESTADOS FUZZY -> $ s = (s_1,s_2,s_3,s_4,s_5) \ \ onde\ \ i=1...5 \\ \text{ indica cada tipo de placa de acordo com a densidade da mesma.} \\ $ 



$$\text{ Estados definem a
densidade da placa onde: }\\ s_1 = 20\% ,s_2=40\%,s_3=60\%,s_4=80\%,s_5=100\% $$



TRÊS CONJUNTOS FUZZY DE "ESTADOS DA NATUREZA""
 -> $F_1 = \text{Low-Density PCP},F_2 =
\text{Medium-Density PCP},F_3 = \text{High-Density PCP} $

Alternativas do Modelo: $\ \ A_1 = \text{2-Layer PCB},\ \ A_2 = \text{4-Layer PCB},\ \ A_3 = \text{6-Layer PCB}$

Novos Dados: $x=(x_1,x_2,x_3,x_4,x_5) \ \ \text{onde: }x_1=100\ \ nós,\ \ x_2=200\ \ nós,\ \ x_3=300\ \ nós ,\ \ x_4=400\ \ nós ,\ \ x_5=500\ \ nós $

Sistema ortogonal de informação fuzzy -> 3 conjuntos linguísticos:

$$\\ \\ M_1,M_2,M_3 \ \  \text{onde: }M_1-\text{
Baixo número de nós(menos que 300) },\ \ M_2-\text{ Médio número de nós(entre 300) },M_3 -\text{ Alto
número de nós(mais que 300)}$$

Probabilidade de cada Estado: $p(s_1) = 0.2,p(s_2) = 0.3,p(s_3) = 0.3,p(s_4) = 0.1,p(s_5) = 0.1$

    

In [54]:
#MATRIZ DE UTILIDADE ESTADO Fuzzy ALTERNATIVA (Alternativas_i X SETFUZZY_j)
#TABELA 9.9
MU= np.array([[10., 3., 0.],[4., 9., 6.],[1.0,7.0,10.0]])
MU

array([[ 10.,   3.,   0.],
       [  4.,   9.,   6.],
       [  1.,   7.,  10.]])

$$\large\text{Vamos definir a matriz de utilidade MU que expressa a utilidade para um A_i dado F_j}$$

$$\large{\text{Vamos definir a matriz de Pertinência para cada conjunto fuzzy F_i para os estados s_j}}$$

In [3]:
#Matriz ortogonal de conjuntos fuzzy (Fuzzy_i por S_j)
#TABELA 9.10
FS = np.array([[1.,0.5,0,0,0],[0.,0.5,1,0.5,0],[0.,0.,0.,0.5,1.]])
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

$$\large{\text{Vamos definir a matriz de Pertinência para cada conjunto de Informação fuzzy M_i para os dados x_j}}$$

In [4]:
#TABELA 9.11
#Conjuntos de informação fuzzy ortogonais relaciona os
# M's(conjuntos fuzzy de acordo com os nodos +-300) aos x's(qtd exata de nodos)(M_i X DADOX_j)
FM = np.array([[1,0.4,0.,0.,0.],[0.,0.6,1.,0.6,0],[0.,0.,0.,0.4,1.]])
FM

array([[ 1. ,  0.4,  0. ,  0. ,  0. ],
       [ 0. ,  0.6,  1. ,  0.6,  0. ],
       [ 0. ,  0. ,  0. ,  0.4,  1. ]])

$$\large{\text{Vamos definir a matriz de Probabilidade Condicional para informações incertas }\\  p(x_j|s_i) \\ \text{Probabilidade(linhas) X Novos Dados(colunas) - Probabilidade de um nós, dado  uma instância}} $$

In [5]:
#TABELA 9.12  -    (p(x_j|s_i)x DATAX_j)
CPUnc = np.array([[ 0.44,0.35,0.17,0.04,0 ],[0.26,0.32,0.26,0.13,0.03],
[0.12,0.23,0.30,0.23,0.12],[0.03,0.13,0.26,0.32,0.26],[0,0.04,0.17,0.35,0.44]])
CPUnc

array([[ 0.44,  0.35,  0.17,  0.04,  0.  ],
       [ 0.26,  0.32,  0.26,  0.13,  0.03],
       [ 0.12,  0.23,  0.3 ,  0.23,  0.12],
       [ 0.03,  0.13,  0.26,  0.32,  0.26],
       [ 0.  ,  0.04,  0.17,  0.35,  0.44]])

$$\large{\text{Probabilidade Condicional para informações PERFEITAS }\\  p(x_j|s_i) \\ \text{Probabilidade(linhas) X Novos Dados(colunas) - Probabilidade de um nó, dado  uma instância}} $$

In [37]:
#TABELA 9.13
CPPer = array([[1.0,0.,0.,0.,0.],[0.0,1.,0.,0.,0.],[0.0,0.,1.,0.,0.],
[0.0,0.,0.,1.,0.],[0.0,0.,0.,0.,1.]])
CPPer

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

<hr/>
<hr/>

$$\large{\text{Agora temos informações suficientes para iniciar as análises probabilísticas e estabelecer uma tomada de decisão}}$$
<hr/>
<hr/>



$$\Large{\text{CASO 1: Ações e Estados CRISP ( Nítidos / bem definidos / não-fuzzy )}}$$
<hr/>
___________________________________________________

$\large{\text{1.1 - Utilidade e melhor opção dada nenhuma informação}}$

$\large{\text{Primeiramente vamos calcular a utilidade esperada e depois encontrar a opção ótima}}$

In [6]:
# Vetor de Probabilidades para os estados "s"
Ps = np.array([0.2,0.3,0.3,0.1,0.1])
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

In [7]:
#Tabela 9.14 ( Valores de utilidade)
#depois analisar a tabela de utilidade para cara uma das alternativas Ai
#de acordo com os estados s'i
Ut = array([[10.,8.,6.,2.,0.],[4.,6.,9.,6.,4.],[1.,2.,6.,8.,10]])
Ut

array([[ 10.,   8.,   6.,   2.,   0.],
       [  4.,   6.,   9.,   6.,   4.],
       [  1.,   2.,   6.,   8.,  10.]])

In [8]:
def UtiEsp1(A,P):
    vetUT = np.dot(A,P)
    opcao = np.argmax(vetUT)
    print("A melhor alternativa é :",opcao+1)
    return vetUT
    
    

In [9]:
EUX0 = UtiEsp1(Ut,Ps)
EUX0

A melhor alternativa é : 1


array([ 6.4,  6.3,  4.4])

In [10]:
EUX0[0]

6.4000000000000004

$\large{\text{1.2 - Utilidade e melhor opção dada incerteza e informação perfeita}}$

$\large{\text{ a) - Informações Probabilísticas}}$

In [11]:
# PRIMEIRAMENTE É CALCULAR AS PROBABILIDADE MARGINAIS CONDICIONAIS  -  SOMATÓRIO DE CADA VALOR PROBABILÍSTICO INCERTO
#ELE NÃO DIZ COMO FAZ
# MATRIZ DE PROBABILIDADE CONDICIONAL 
CPUnc 


array([[ 0.44,  0.35,  0.17,  0.04,  0.  ],
       [ 0.26,  0.32,  0.26,  0.13,  0.03],
       [ 0.12,  0.23,  0.3 ,  0.23,  0.12],
       [ 0.03,  0.13,  0.26,  0.32,  0.26],
       [ 0.  ,  0.04,  0.17,  0.35,  0.44]])

In [12]:
#VETOR DE PROBABILIDADE

Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

$${\text{VAMOS ENCONTRAR A "PROBABILIDADE MARGINAL" PELO TEOREMA DA PROBABILIDADE TOTAL}}$$

In [13]:
def ProMarg(Mat,P): 
    l,c = Mat.shape
    Pm = np.zeros((l))
    for j in range(l):
        for i in range(l):
            Pm[j] = Pm[j] + Mat[i,j]*P[i]
    return Pm


            
    

In [14]:
#A PROBABILIDADE DE UM ESTADO X_i OCORRER
Pm = ProMarg(CPUnc,Ps)
Pm

array([ 0.205,  0.252,  0.245,  0.183,  0.115])

$$\large{\text{APLICANDO O TEOREMA DE BAYES}}$$

In [16]:
# Agora vamos calcular as matrizes condicionais. 
def ProbCond(A,P):
    #Vamos Calcular as probabilidades Marginais pelo teorema da probabilidade total.
    l,c = A.shape
    Pm = np.zeros((l))
    for j in range(l):
        for i in range(l):
            Pm[j] = Pm[j] + A[i,j]*P[i]
    ConPr = np.zeros((l,l))
    for j in range(l):
         for i in range(l):
            ConPr[i,j] = ((A[i,j]*P[i])/Pm[j])
    return ConPr
    


$$\Large{\text{Matriz das probabilidades condicionais}}$$ 

In [19]:
MPCond = ProbCond(CPUnc,Ps) # X_i X s_j
MPCond

array([[ 0.42926829,  0.27777778,  0.13877551,  0.04371585,  0.        ],
       [ 0.3804878 ,  0.38095238,  0.31836735,  0.21311475,  0.07826087],
       [ 0.17560976,  0.27380952,  0.36734694,  0.37704918,  0.31304348],
       [ 0.01463415,  0.0515873 ,  0.10612245,  0.17486339,  0.22608696],
       [ 0.        ,  0.01587302,  0.06938776,  0.19125683,  0.3826087 ]])

In [20]:
sum(MPCond[:,0])

0.99999999999999989

$$\Large{\text{Vamos determinar o vetor de utilidade esperada }}$$ 

In [22]:
Ut # Alternativas_i X S_j (ESTADOS)

array([[ 10.,   8.,   6.,   2.,   0.],
       [  4.,   6.,   9.,   6.,   4.],
       [  1.,   2.,   6.,   8.,  10.]])

In [23]:
MUtil = np.dot(Ut,MPCond)
MUtil

array([[ 8.4195122 ,  7.57142857,  6.35102041,  4.75409836,  2.95652174],
       [ 5.66829268,  6.23412698,  6.68571429,  6.66120219,  6.17391304],
       [ 2.36097561,  3.25396825,  4.52244898,  6.04371585,  7.66956522]])

In [27]:
def UtiEsp(A):
    l,c = A.shape
    VetUti = np.zeros((c))
    Alternativas = np.zeros((c))
    for j in range(c):
        VetUti[j] = np.max(A[:,j])
        Alternativas[j] = np.argmax(A[:,j])+1
    return VetUti,Alternativas
        
        
        

In [30]:
Eux,Alter = UtiEsp(MUtil)


In [31]:
#Vetor de utilidade esperada 
Eux

array([ 8.4195122 ,  7.57142857,  6.68571429,  6.66120219,  7.66956522])

In [137]:
#Alternativas
Alter

array([ 1.,  1.,  2.,  2.,  3.])

Logo, para o dado X1 deve ser escolhida a alternativa A1 (PCB de duas camadas). Para X2 deve ser escolhida a alternativa A2 (PCB de duas camadas). Para X3 o PCB de 4 camadas e assim sucessivamente para os valores do vetor UtiEsp.

$$\Large{\text{Determinar a utilidade total }}$$ 

In [33]:
UitTotal = np.dot(Eux,Pm)
UitTotal

7.3729999999999993

${\text{Para determinar o valor da informação, analisamos quanto ele diferere do ótimo encontrado com ações e estados bem definidos.  }}$

In [34]:
VALOR = 7.3729 - 6.4
VALOR

0.9728999999999992

COMO A DIFERENÇA FOI MUITO PEQUENA, NÃO HÁ UMA CONTRIBUIÇÃO SIGNIFICANTE AO MODELO PERANTE ÀS NOVAS INFORMAÇÕES ADICIONADAS.

$\large{\text{ b) - Informações Probabilísticas Perfeitas}}$

In [35]:
# USA A MESMA UTILIDADE (ALTERNATIVAS_I X S_J)
Ut

array([[ 10.,   8.,   6.,   2.,   0.],
       [  4.,   6.,   9.,   6.,   4.],
       [  1.,   2.,   6.,   8.,  10.]])

In [38]:
#informações probabilísticas perfeitas
CPPer

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [39]:
# Mesma probabildade sobre os estados
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

$$\large{\text{ Determinar a utilidade esperada}}$$

In [40]:
# Vamos determinar a utilidade Esperada ( Alternativas Fuzzy X Estados)
MUtil2 = np.dot(Ut,CPPer)
MUtil2

array([[ 10.,   8.,   6.,   2.,   0.],
       [  4.,   6.,   9.,   6.,   4.],
       [  1.,   2.,   6.,   8.,  10.]])

In [41]:
#Agora determinar a utilidade e as alternativas ótimas
Eux2,Alter2 = UtiEsp(MUtil2)


In [42]:
Eux2

array([ 10.,   8.,   9.,   8.,  10.])

In [43]:
#Qual alternativa escolher para cada tipo de dado
Alter2

array([ 1.,  1.,  2.,  3.,  3.])

$$\large{\text{Utilidade Máxima Esperada}}$$

In [44]:
UTMAX = np.dot(Eux2,Ps)
UTMAX

8.8999999999999986

$$\large{\text{VALOR DA INFORMAÇÃO PROBABILÍSTA PERFEITA}}$$

In [45]:
VPP = UTMAX - EUX0[0]
VPP

2.4999999999999982

<hr/>
___________________________________________________
$$\Large{\text{CASO 2: Ações e Estados Fuzzy}}$$
<hr/>
___________________________________________________

$\large{\text{ 1) - Utilidade e ótimo dada nenhuma informação}}$

In [46]:
# Dada a utilidade
Ut

array([[ 10.,   8.,   6.,   2.,   0.],
       [  4.,   6.,   9.,   6.,   4.],
       [  1.,   2.,   6.,   8.,  10.]])

In [49]:
# MATRIZ FUZZY PARA O ESTADOS 's' (F_i X S_j) Fuzzy 'F' por estados 's'
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

In [50]:
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

In [52]:
# PROBABILIDADES DE CADA CONJUNTO FUZZY DE ACORDO COM CADA ESTADO 'S'
PPF = np.dot(FS,Ps)
PPF

array([ 0.35,  0.5 ,  0.15])

In [56]:
#MATRIZ DADA  -  RELACIONA A_i X F_j 
MU

array([[ 10.,   3.,   0.],
       [  4.,   9.,   6.],
       [  1.,   7.,  10.]])

In [57]:
#VETOR DE UTILIDADE ESPERADA
np.dot(MU,PPF)

array([ 5.  ,  6.8 ,  5.35])

In [58]:
# Utilidade Esperada 
UtF = UtiEsp1(MU,PPF)
UtF

A melhor alternativa é : 2


array([ 5.  ,  6.8 ,  5.35])

In [180]:
# ÓTIMO
UtF[1]

6.7999999999999998

$\large{\text{ $\large{\text{ 2) - Utilidade e ótimo dada informação incerta e perfeita}}$}}$

$\text{a) Informação Probabilística ( INCERTA )}$

In [181]:
# MATRIZ FUZZY PARA O ESTADOS 's' ( F_i X S_j)
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

In [59]:
#MATRIZ DE PROBABILIDADE CONDICIONAL p(x|s)_i X DATAX_j
CPUnc

array([[ 0.44,  0.35,  0.17,  0.04,  0.  ],
       [ 0.26,  0.32,  0.26,  0.13,  0.03],
       [ 0.12,  0.23,  0.3 ,  0.23,  0.12],
       [ 0.03,  0.13,  0.26,  0.32,  0.26],
       [ 0.  ,  0.04,  0.17,  0.35,  0.44]])

In [60]:
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

In [62]:
Pm

array([ 0.205,  0.252,  0.245,  0.183,  0.115])

$$\large{\text{MATRIZ DE PROBABILIDADE POSTERIOR FUZZY}}$$

<img src="Images/fig952a.png">

In [64]:
def PoPrF(F,U,P,PM):
    l,c = F.shape
    MP = np.zeros((c,l))
    for i in range(l):
        for k in range(c):
            soma = 0
            for j in range(c):
                soma = soma + (F[i,j]*U[j,k]*P[j])
            MP[k,i] = (soma/PM[k])
    return MP

In [65]:
# VAMOS CALCULAR A MATRIZ DE PROBABILIDADE INCERTA (x_i ) X (F_j)
MPInc = PoPrF(FS,CPUnc,Ps,Pm)
MPInc

array([[ 0.6195122 ,  0.37317073,  0.00731707],
       [ 0.46825397,  0.49007937,  0.04166667],
       [ 0.29795918,  0.57959184,  0.12244898],
       [ 0.15027322,  0.57103825,  0.27868852],
       [ 0.03913043,  0.46521739,  0.49565217]])

Agora vamos calcular a utilidade esperada para cada alternativa fuzzy com informação probabilística
<hr\>

In [67]:
MPInc

array([[ 0.6195122 ,  0.37317073,  0.00731707],
       [ 0.46825397,  0.49007937,  0.04166667],
       [ 0.29795918,  0.57959184,  0.12244898],
       [ 0.15027322,  0.57103825,  0.27868852],
       [ 0.03913043,  0.46521739,  0.49565217]])

In [69]:
Multi3 = np.dot(MPInc,MU.T)# (x_i) X(A_j)
Multi3

array([[ 7.31463415,  5.8804878 ,  3.30487805],
       [ 6.15277778,  6.53373016,  4.31547619],
       [ 4.71836735,  7.14285714,  5.57959184],
       [ 3.21584699,  7.41256831,  6.93442623],
       [ 1.78695652,  7.3173913 ,  8.25217391]])

### AGORA AS LINHAS QUE SÃO AS OPÇÕES- Preciso avaliar a "melhor opção" sobre as linhas e não sobre as colunas

In [70]:
def UtiEspX(A):
    l,c = A.shape
    VetUti = np.zeros((l))
    Alternativas = np.zeros((l))
    for j in range(l):
        VetUti[j] = np.max(A[j,:])
        Alternativas[j] = np.argmax(A[j,:])+1
    return VetUti,Alternativas


In [71]:
Eux1,Alter1 = UtiEspX(Multi3)
Eux1

array([ 7.31463415,  6.53373016,  7.14285714,  7.41256831,  8.25217391])

In [72]:
Alter1

array([ 1.,  2.,  2.,  2.,  3.])

$\normalsize{\text{Há vários modos de interpretar "A MELHOR OPÇÃO"}}$

$$\large{\text{AGORA VAMOS ENCONTRAR O ÓTIMO GLOBAL}}$$

In [73]:
Otimo= np.dot(Eux1,Pm)
Otimo

7.2015000000000002

$$\large{\text{Por fim, o valor da informação probabilística incerta }}$$

In [74]:
#Matriz de ótimos para as alternivas fuzzy
#uso o maior dela
UtF

array([ 5.  ,  6.8 ,  5.35])

In [75]:
VALORInF = Otimo - UtF[1]
VALORInF

0.40150000000000041

## Cálculo da Probabilidade da Informação perfeita

In [103]:
#matriz dos conjuntos fuzzy para os estados(F_i)X(s_j)
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

In [142]:
FS.T

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  0.5,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  0. ,  1. ]])

In [104]:
#informações probabilísticas perfeitas(p(x_i|s_i)X (DADO-X_j))
CPPer

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [105]:
# probabilidade para os estados
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

In [106]:
#probabilidade marginal
Pm

array([ 0.205,  0.252,  0.245,  0.183,  0.115])

In [107]:
Pm1 = 1/Pm
Pm1

array([ 4.87804878,  3.96825397,  4.08163265,  5.46448087,  8.69565217])

In [111]:
# Estados x_i por F_j
MPrPerInf = (np.dot(CPPer,FS.T))
MPrPerInf

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  0.5,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  0. ,  1. ]])

In [112]:
# A_i X F_j ( VOU USAR O TRANSPOSTA DESSE CARA)
MU

array([[ 10.,   3.,   0.],
       [  4.,   9.,   6.],
       [  1.,   7.,  10.]])

In [114]:
# x_i por A_j
UtFA = np.dot(MPrPerInf,MU.T)
UtFA

array([[ 10. ,   4. ,   1. ],
       [  6.5,   6.5,   4. ],
       [  3. ,   9. ,   7. ],
       [  1.5,   7.5,   8.5],
       [  0. ,   6. ,  10. ]])

In [116]:
#A melhor utilidade para cada x_i
UTPerInf = UtiEspX(UtFA)
UTPerInf

(array([ 10. ,   6.5,   9. ,   8.5,  10. ]), array([ 1.,  1.,  2.,  3.,  3.]))

In [122]:
# POR FIM A UTILIDADE ESPERADA
OTIM =  np.dot(UTPerInf[0],Ps)
OTIM

8.5

$$\large{\text{Agora vamos calcular o valor de informação probabilística perfeita}}$$

In [123]:
VALORInFPP = OTIM -UtF[1]
VALORInFPP

1.7000000000000002

## c) Informação Fuzzy

$\normalsize{\text{Matriz de probabilidade para os estados fuzzy de acordo com as informações
fuzzy}}$

$$\normalsize{\text{PROBLEMA -  ELE NÃO DIZ COMO ACHAR UMA MATRIZ DE ESTADOS FUZZY SOBRE ALTERNATIVAS FUZZY}}$$

<hr\>
<hr\>
$$\Large{\text{MATRIZ DE ESTADOS FUZZY SOBRE ALTERNATIVAS FUZZY}}$$
<hr\>
<hr\>

<img src="Images/fig952B.png">

In [151]:
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

In [152]:
FM

array([[ 1. ,  0.4,  0. ,  0. ,  0. ],
       [ 0. ,  0.6,  1. ,  0.6,  0. ],
       [ 0. ,  0. ,  0. ,  0.4,  1. ]])

In [164]:
Ps

array([ 0.2,  0.3,  0.3,  0.1,  0.1])

In [153]:
Pm

array([ 0.205,  0.252,  0.245,  0.183,  0.115])

In [154]:
#(p(x_j|s_i)x DATAX_j)
CPUnc

array([[ 0.44,  0.35,  0.17,  0.04,  0.  ],
       [ 0.26,  0.32,  0.26,  0.13,  0.03],
       [ 0.12,  0.23,  0.3 ,  0.23,  0.12],
       [ 0.03,  0.13,  0.26,  0.32,  0.26],
       [ 0.  ,  0.04,  0.17,  0.35,  0.44]])

In [165]:
l,c = CPUnc.shape
TR = np.zeros((l,c))
for i in range(l):
    TR[i,:] = CPUnc[i,:]*Ps[0]
TR

array([[ 0.088,  0.07 ,  0.034,  0.008,  0.   ],
       [ 0.052,  0.064,  0.052,  0.026,  0.006],
       [ 0.024,  0.046,  0.06 ,  0.046,  0.024],
       [ 0.006,  0.026,  0.052,  0.064,  0.052],
       [ 0.   ,  0.008,  0.034,  0.07 ,  0.088]])

In [166]:
FM

array([[ 1. ,  0.4,  0. ,  0. ,  0. ],
       [ 0. ,  0.6,  1. ,  0.6,  0. ],
       [ 0. ,  0. ,  0. ,  0.4,  1. ]])

In [167]:
TR2 = np.dot(FM,TR)
TR2

array([[ 0.1088,  0.0956,  0.0548,  0.0184,  0.0024],
       [ 0.0588,  0.1   ,  0.1224,  0.1   ,  0.0588],
       [ 0.0024,  0.0184,  0.0548,  0.0956,  0.1088]])

In [168]:
FS

array([[ 1. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  1. ]])

In [169]:
TR3 = np.dot(FS,TR2.T)
TR3

array([[ 0.1566,  0.1088,  0.0116],
       [ 0.1118,  0.2224,  0.1118],
       [ 0.0116,  0.1088,  0.1566]])

In [170]:
divid

array([ 0.3058,  0.506 ,  0.1882])

In [173]:
l,c = TR3.shape
Mfinal = np.zeros((l,c))
for i in range(l):
    Mfinal[:,i] = TR3[:,i]/divid[i]
Mfinal
    

array([[ 0.51209941,  0.21501976,  0.06163656],
       [ 0.36559843,  0.43952569,  0.59404888],
       [ 0.03793329,  0.21501976,  0.83209352]])